name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9'

      - name: Restore dependencies
        run: dotnet restore ./qr-code-generator/qr-code-generator.csproj

      - name: Run unit tests
        run: dotnet test ./qr-code-generator.Test/qr-code-generator.Test.csproj --no-build --verbosity normal

      - name: Build
        run: dotnet publish ./qr-code-generator/qr-code-generator.csproj -c Release -o build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
